{% set name = "ephyviewer" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0251f58d72a2a52d62f70fcb9c807434668e0f60667f0d27f3cfd8f3062b6455

build:
  noarch: python
  number: 0
  entry_points:
    - ephyviewer=ephyviewer.scripts:launch_standalone_ephyviewer
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - matplotlib-base >=2.0
    - numpy
    - pyqt
    - pyqtgraph >=0.10.0
    - python >=3.7
    - scipy
  run_constrained:
    - python-neo >=0.6

test:
  imports:
    - ephyviewer
    - ephyviewer.datasource
    - ephyviewer.icons
    - ephyviewer.tests
  commands:
    - ephyviewer --help

about:
  home: https://github.com/NeuralEnsemble/ephyviewer
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple viewers for ephys signals, events, video and more
  description: |
    ephyviewer is a Python library based on pyqtgraph for building custom
    viewers for electrophysiological signals, video, events, epochs, spike
    trains, data tables, and time-frequency representations of signals. It also
    provides an epoch encoder for creating annotations.
  doc_url: https://ephyviewer.readthedocs.io/
  dev_url: https://github.com/NeuralEnsemble/ephyviewer

extra:
  recipe-maintainers:
    - jpgill86
    - samuelgarcia
